### PR TITLE
Add support for bypassing zones

### PR DESCRIPTION
**Pull request by chatziko**
Adds services to bypass / unbypass zones, which is quite useful in automations.

Requires the following PR for the python lib: https://github.com/caronc/ultrasync/pull/17

### CODE REVIEW

**Comment by chatziko** [comment]
Rebased on the latest master.

**Comment by chatziko** [comment]
Thanks for merging!

For this to trully work I guess you also need to release a new version of the python library, and update manifest.json.

**Comment by caronc** [comment]
I don't think so, the community service seems to pick up on just new merges to the master as a new version.  I think you're good, but let me know if you have a problem.  If anything, i could see value in bumping the version of the actual `core` of ultrasync  I can go do that now.

**Comment by chatziko** [comment]
I'm confused... the HA integration (`ha-ultrasync` repo) needs the latest changes of the python lib (`ultrasync` repo). I assumed that the python lib is automatically installed by HA dueto the following line in `custom_components/ultrasync/manifest.json`.
```
"requirements": ["ultrasync==0.9.4"],
```
Doesn't this need to change to pick up the changes in the python lib?

**Comment by caronc** [comment]
Now that you've gotten your hands dirty with how the logic works, i'd love to separate the areas up.  but to be backwards compatible, it should behave the way it does now.

Soo have a default area of `None` that when specified applies to all areas... but otherwise if set to `1`, `2` etc, then only the chosen area is targeted.  But you're very correct with your point about area support. It ties back to [this issue](https://github.com/caronc/ultrasync/issues/13) that i have not tackled.

**Comment by chatziko** [comment]
SInce we're discussing new features (abusing the PR :smile: ), I'd like your input on how easily the following could be implemented:
1. Reading the account that disarmed the alarm (useful for notifications of "guest" accounts).
2. Reading the zone that triggered the alarm (useful to known where to look)
  
    These two are available in the web interface under `Event History` (maybe also elsewhere?)

3. Manually triggering the alarm (useful eg for checking cameras etc, and manually trigger if something suspicious is seen).
    
    This I don't know whether it's possible from the web interface (maybe there is some indirect workaround, like enabling some zone to cause a trigger).

Ideas?

**Comment by chatziko** [comment]
Thanks @caronc for the info!

For the moment, I've found a "hack" to trigger the alarm from the web interface. For this we need a zone that is constantly faulted (Not Ready).
1. Bypass the faulted zone before arming
2. Arm the alarm
3. Unbypass the zone while armed, this triggers the alarm since the zone is faulted.

So in theory this can be automated, however there are two issues:
1. We need to have a zone that is constantly faulted. Maybe we can somehow configure one of the unused zones to be constantly faulted?
2. If the user tries to manually arm the alarm, the faulted zone will prevent arming. A solution could be to configure the zone as "auto-bypass" (allow to arm when the zone is faulted), but in this case the trigger-hack doesn't work! The zone must be __manually__ bypassed in order for the unbypass action to trigger the alarm.

So it's something, but far from ideal.

Related question: is there some way to disable the alarm siren while testing? It's crazy when you do something and a loud siren triggers.

**Comment by thanomichalis** [comment]
@chatziko 

Hello, how you managed to work the bypass/unbypass service?

**Pull request merged**
